# Generated by Django 3.2.6 on 2021-09-20 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katha_no', models.CharField(help_text='Enter Katha Number..', max_length=50)),
                ('new_passbook_no', models.CharField(help_text='Enter passbook Number..', max_length=50)),
                ('document_no', models.CharField(help_text='Enter Extent document number..', max_length=100, unique=True)),
                ('aadhar_no', models.BigIntegerField(help_text='Enter Aadhar Number..', unique=True)),
                ('pass_photo', models.ImageField(help_text='Upload Passport size Image..', upload_to='app/')),
                ('passbook_photo', models.ImageField(help_text='Upload passbook Image..', upload_to='app/')),
                ('Note', models.TextField(help_text='please enter note..')),
            ],
        ),
        migrations.CreateModel(
            name='New_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_photos', models.FileField(upload_to='app/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.document_details')),
            ],
        ),
        migrations.CreateModel(
            name='Plots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot', models.CharField(blank=True, max_length=50, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.new_project')),
            ],
        ),
        migrations.CreateModel(
            name='New_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_no', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mail_id', models.EmailField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('survey_no', models.CharField(max_length=50)),
                ('land_extent', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('AP', 'ANDHRA PRADESH'), ('TS', 'TELANGANA')], max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.new_project')),
            ],
        ),
        migrations.CreateModel(
            name='Extent_sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_plot', models.CharField(blank=True, max_length=50, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.document_details')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.new_project')),
            ],
        ),
        migrations.AddField(
            model_name='document_details',
            name='plot_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_nos', to='app.new_registration'),
        ),
        migrations.AddField(
            model_name='document_details',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.new_project'),
        ),
    ]
