# Generated by Django 3.2.6 on 2021-08-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_registration',
            old_name='farm_name',
            new_name='project_name',
        ),
    ]
