# Generated by Django 3.2.6 on 2021-08-10 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_farm_name_new_registration_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_registration',
            old_name='house_no',
            new_name='survey_no',
        ),
        migrations.RemoveField(
            model_name='new_registration',
            name='street',
        ),
        migrations.AddField(
            model_name='new_registration',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
