# Generated by Django 3.2.6 on 2021-08-14 12:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210810_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katha_no', models.CharField(help_text='Enter Katha Number..', max_length=50, unique=True)),
                ('new_passbook_no', models.CharField(help_text='Enter passbook Number..', max_length=50, unique=True)),
                ('extent_document_no', models.CharField(help_text='Enter Extent document number..', max_length=100, null=True, unique=True)),
                ('aadhar_no', models.BigIntegerField(help_text='Enter Aadhar Number..', unique=True, validators=[django.core.validators.MaxLengthValidator(12), django.core.validators.MinLengthValidator(1)])),
                ('aadhar_photo', models.FileField(blank=True, help_text='Upload Aadhar Image..', null=True, upload_to='app/')),
                ('passbook_photo', models.FileField(blank=True, help_text='Upload passbook Image..', null=True, upload_to='app/')),
                ('document_photos', models.FileField(blank=True, help_text='Upload document Images..', null=True, upload_to='app/')),
                ('Note', models.TextField(help_text='please enter note..')),
                ('plot_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_nos', to='app.new_registration')),
                ('survey_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_nos', to='app.new_registration')),
            ],
        ),
    ]
