# Generated by Django 3.2.6 on 2021-08-14 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_document_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_details',
            name='survey_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_survey_nos', to='app.new_registration'),
        ),
    ]
