# Generated by Django 3.2.6 on 2021-08-14 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_document_details_survey_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_details',
            name='survey_no',
        ),
        migrations.AddField(
            model_name='document_details',
            name='project_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.new_project', unique=True),
            preserve_default=False,
        ),
    ]
