# Generated by Django 3.2.6 on 2021-08-14 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210814_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_details',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.new_project'),
        ),
    ]
