# Generated by Django 3.2.6 on 2021-08-15 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_document_details_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_details',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.new_project'),
        ),
    ]
