# Generated by Django 3.2.6 on 2021-08-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_document_details_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_details',
            name='aadhar_no',
            field=models.BigIntegerField(help_text='Enter Aadhar Number..', unique=True),
        ),
    ]
