# Generated by Django 3.2.6 on 2021-08-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_document_details_aadhar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_details',
            name='aadhar_photo',
            field=models.ImageField(blank=True, help_text='Upload Aadhar Image..', null=True, upload_to='app/'),
        ),
        migrations.AlterField(
            model_name='document_details',
            name='document_photos',
            field=models.ImageField(blank=True, help_text='Upload document Images..', null=True, upload_to='app/'),
        ),
        migrations.AlterField(
            model_name='document_details',
            name='passbook_photo',
            field=models.ImageField(blank=True, help_text='Upload passbook Image..', null=True, upload_to='app/'),
        ),
    ]
