# Generated by Django 3.2.6 on 2021-08-18 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210818_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_details',
            name='document_photos',
            field=models.FileField(blank=True, help_text='Upload document Images..', null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.document_details')),
            ],
        ),
    ]
