# Generated by Django 3.2.6 on 2021-08-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210818_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document_details',
            name='document_photos',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.FileField(upload_to='app/'),
        ),
    ]
