# Generated by Django 3.2.6 on 2021-08-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210818_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='images',
            new_name='document_photos',
        ),
    ]
