# Generated by Django 3.2.6 on 2021-08-20 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_images_postimage_document_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_details',
            name='aadhar_photo',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, help_text='Upload Aadhar Image..', upload_to='app/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document_details',
            name='extent_document_no',
            field=models.CharField(default=django.utils.timezone.now, help_text='Enter Extent document number..', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document_details',
            name='passbook_photo',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, help_text='Upload passbook Image..', upload_to='app/'),
            preserve_default=False,
        ),
    ]
