# Generated by Django 3.2.6 on 2021-09-07 09:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210820_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document_details',
            old_name='extent_document_no',
            new_name='document_no',
        ),
        migrations.RemoveField(
            model_name='document_details',
            name='aadhar_photo',
        ),
        migrations.AddField(
            model_name='document_details',
            name='pass_photo',
            field=models.ImageField(default=datetime.datetime(2021, 9, 7, 9, 32, 0, 655335, tzinfo=utc), help_text='Upload Passport size Image..', upload_to='app/'),
            preserve_default=False,
        ),
    ]
